---

# Generate certificates for E2Guardian SSL man-in-the-middle usage.

# Make sure certificate paths exist.
- name: CERTS | Cert paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ e2g_conf_daemonuser }}"
    group: "{{ e2g_conf_daemongroup }}"
    mode: "0750"
  loop:
    - "{{ e2g_conf_cacertificatepath | dirname }}"
    - "{{ e2g_conf_caprivatekeypath | dirname }}"
    - "{{ e2g_conf_generatedcertpath }}"
  when: item is defined

# Generate certificates.
- name: CERTS | Private keys generated
  community.crypto.openssl_privatekey:
    path: "{{ item }}"
    size: "{{ e2g_cert_key_size }}"
    type: "{{ e2g_cert_type }}"
    owner: "{{ e2g_conf_daemonuser }}"
    group: "{{ e2g_conf_daemongroup }}"
    mode: "0400"
  loop:
    - "{{ e2g_conf_caprivatekeypath }}"
    - "{{ e2g_conf_certprivatekeypath }}"
  when: item is defined
  notify: restart-e2guardian

- name: CERTS | CA cert generated
  community.crypto.x509_certificate:
    path: "{{ e2g_conf_cacertificatepath }}"
    privatekey_path: "{{ e2g_conf_caprivatekeypath }}"
    provider: selfsigned
    owner: "{{ e2g_conf_daemonuser }}"
    group: "{{ e2g_conf_daemongroup }}"
    mode: "0400"
  notify: restart-e2guardian

- name: CERTS | CSR created for CA cert
  community.crypto.openssl_csr:
    path: "{{ e2g_conf_cacertificatepath }}.csr"
    privatekey_path: "{{ e2g_conf_caprivatekeypath }}"
    common_name: "{{ e2g_ca_name }}"
    owner: "{{ e2g_conf_daemonuser }}"
    group: "{{ e2g_conf_daemongroup }}"
    mode: "0400"
  notify: restart-e2guardian

- name: CERTS | CA cert signed using CSR
  community.crypto.x509_certificate:
    path: "{{ e2g_conf_cacertificatepath }}"
    csr_path: "{{ e2g_conf_cacertificatepath }}.csr"
    privatekey_path: "{{ e2g_conf_caprivatekeypath }}"
    provider: selfsigned
    owner: "{{ e2g_conf_daemonuser }}"
    group: "{{ e2g_conf_daemongroup }}"
    mode: "0400"
  notify: restart-e2guardian

- name: CERTS | CA cert copied to webserver dir
  ansible.builtin.copy:
    src: "{{ e2g_conf_cacertificatepath }}"
    dest: /var/www/e2guardian/e2g-ca-cert.pem
    remote_src: true
    owner: www-data
    group: www-data
    mode: "0440"
