---

# Generate certificates for E2Guardian's SSL man-in-the-middle mode.
# Certs are only generated if they don't already exist in order to maintain idempotence.

- name: CERTS | Cert paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ e2g_conf_daemonuser }}"
    group: "{{ e2g_conf_daemongroup }}"
    mode: "0750"
  when: item is defined
  loop:
    - "{{ e2g_conf_cacertificatepath | dirname }}"
    - "{{ e2g_conf_caprivatekeypath | dirname }}"
    - "{{ e2g_conf_generatedcertpath }}"

- name: CERTS | Check for cert private key
  ansible.builtin.stat:
    path: "{{ e2g_conf_certprivatekeypath }}"
  register: cert_private_key_path

- name: CERTS | Cert private key generated
  community.crypto.openssl_privatekey:
    path: "{{ e2g_conf_caprivatekeypath }}"
    size: "{{ e2g_cert_key_size }}"
    type: "{{ e2g_cert_type }}"
    owner: "{{ e2g_conf_daemonuser }}"
    group: "{{ e2g_conf_daemongroup }}"
    mode: "0400"
  when: cert_private_key_path.stat.readable is not defined
  notify: restart-e2guardian

- name: CERTS | Check for CA private key
  ansible.builtin.stat:
    path: "{{ e2g_conf_caprivatekeypath }}"
  register: ca_private_key_path

- name: CERTS | CA private key generated
  community.crypto.openssl_privatekey:
    path: "{{ e2g_conf_caprivatekeypath }}"
    size: "{{ e2g_cert_key_size }}"
    type: "{{ e2g_cert_type }}"
    owner: "{{ e2g_conf_daemonuser }}"
    group: "{{ e2g_conf_daemongroup }}"
    mode: "0400"
  when: ca_private_key_path.stat.readable is not defined
  notify: restart-e2guardian

- name: CERTS | Check for CA cert
  ansible.builtin.stat:
    path: "{{ e2g_conf_cacertificatepath }}"
  register: ca_path

- name: CERT | CA cert generated
  community.crypto.x509_certificate:
    path: "{{ e2g_conf_cacertificatepath }}"
    privatekey_path: "{{ e2g_conf_caprivatekeypath }}"
    provider: selfsigned
    owner: "{{ e2g_conf_daemonuser }}"
    group: "{{ e2g_conf_daemongroup }}"
    mode: "0400"
  when: ca_path.stat.readable is not defined
  notify: restart-e2guardian

- name: CERTS | Check for CSR
  ansible.builtin.stat:
    path: "{{ e2g_conf_cacertificatepath }}.csr"
  register: csr_path

- name: CERTS | CSR generated
  community.crypto.openssl_csr:
    path: "{{ e2g_conf_cacertificatepath }}.csr"
    privatekey_path: "{{ e2g_conf_caprivatekeypath }}"
    common_name: "{{ e2g_ca_name }}"
    owner: "{{ e2g_conf_daemonuser }}"
    group: "{{ e2g_conf_daemongroup }}"
    mode: "0400"
  register: csr_created
  when: csr_path.stat.readable is not defined
  notify: restart-e2guardian

- name: CERTS | CA cert signed using CSR
  community.crypto.x509_certificate:
    path: "{{ e2g_conf_cacertificatepath }}"
    csr_path: "{{ e2g_conf_cacertificatepath }}.csr"
    privatekey_path: "{{ e2g_conf_caprivatekeypath }}"
    provider: selfsigned
    owner: "{{ e2g_conf_daemonuser }}"
    group: "{{ e2g_conf_daemongroup }}"
    mode: "0400"
  when: csr_created.changed
  notify: restart-e2guardian

- name: CERTS | Check for webserver dir
  ansible.builtin.stat:
    path: /var/www/e2guardian
  register: dir

- name: CERTS | CA cert configured in webserver dir
  block:
    - name: CERTS | CA cert copied to webserver dir
      ansible.builtin.copy:
        src: "{{ e2g_conf_cacertificatepath }}"
        dest: /var/www/e2guardian/cert.pem
        remote_src: true
        owner: www-data
        group: www-data
        mode: "0400"

    - name: CERTS | Symlinks created for CA cert
      ansible.builtin.file:
        src: /var/www/e2guardian/cert.pem
        dest: "{{ item }}"
        state: link
        owner: www-data
        group: www-data
      loop:
        - /var/www/e2guardian/cert
        - /var/www/e2guardian/e2g-ca-cert.pem
        - /var/www/e2guardian/e2g-ca-cert.crt
  when:
    - dir.stat.isdir is defined
    - dir.stat.isdir
