---

# Deploy E2Guardian's main filter lists.

- name: CONFIGURE | Configuration templates deployed
  ansible.builtin.template:
    src: opt/e2guardian/etc/e2guardian/{{ item }}.j2
    dest: "{{ (e2g_install_dir, 'etc', 'e2guardian', item) | path_join }}"
    owner: root
    group: root
    mode: "0640"
  loop:
    - e2guardian.conf
    - lists/authplugins/ipgroups
    - lists/all.group/bannedmimetypelist
    - lists/all.group/bannedregexpurllist
    - lists/all.group/bannedsearchlist
    - lists/all.group/bannedsiteiplist
    - lists/all.group/bannedsitelist
    - lists/all.group/bannedurllist
    - lists/all.group/contentregexplist
    - lists/all.group/exceptionphraselist
    - lists/all.group/exceptionregexpurllist
    - lists/all.group/exceptionsitelist
    - lists/all.group/exceptionurllist
    - lists/all.group/greysitelist
    - lists/all.group/weightedphraselist
  tags: e2g_config_templates
  notify: restart-e2guardian

- name: CONFIGURE | Web templates deployed
  ansible.builtin.template:
    src: opt/e2guardian/share/e2guardian/languages/ukenglish/{{ item }}.j2
    dest: "{{ (e2g_install_dir, 'share', 'e2guardian', 'languages', 'ukenglish', item) | path_join }}"
    owner: root
    group: root
    mode: "0640"
  loop:
    - neterr_template.html
    - template.html
  tags: e2g_config_templates
  notify: restart-e2guardian
