---

# Deploy E2Guardian's main filter lists.

- name: CONFIGURE | Configuration templates deployed
  ansible.builtin.template:
    src: opt/e2g/etc/e2guardian/{{ item }}.j2
    dest: "{{ (e2g_install_dir, 'etc', 'e2guardian', item) | path_join }}"
    owner: root
    group: root
    mode: "0640"
  loop:
    - e2guardian.conf
    - lists/authplugins/ipgroups
    - lists/bannedmimetypelist
    - lists/bannedregexpurllist
    - lists/bannedsiteiplist
    - lists/bannedsitelist
    - lists/bannedurllist
    - lists/contentregexplist
    - lists/exceptionphraselist
    - lists/exceptionregexpurllist
    - lists/exceptionsitelist
    - lists/exceptionurllist
    - lists/greysitelist
    - lists/weightedphraselist
  tags: e2g_config_templates
  notify: restart-e2guardian

- name: CONFIGURE | Web templates deployed
  ansible.builtin.template:
    src: opt/e2g/share/e2guardian/languages/ukenglish/{{ item }}.j2
    dest: "{{ (e2g_install_dir, 'share', 'e2guardian', 'languages', 'ukenglish', item) | path_join }}"
    owner: root
    group: root
    mode: "0640"
    backup: true
  loop:
    - neterr_template.html
    - template.html
  notify: restart-e2guardian
