---

# Deploy E2Guardian's main filter lists.

- name: CONFIGURE | Configuration templates deployed
  ansible.builtin.template:
    src: opt/e2g/etc/e2guardian/{{ item }}.j2
    dest: "{{ e2g_install_dir }}/etc/e2guardian/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - e2guardian.conf
    - lists/authplugins/ipgroups
    - lists/bannedregexpurllist
    - lists/bannedsiteiplist
    - lists/bannedsitelist
    - lists/bannedurllist
    - lists/exceptionphraselist
    - lists/exceptionregexpurllist
    - lists/exceptionsitelist
    - lists/exceptionurllist
    - lists/greysitelist
    - lists/weightedphraselist
  notify: restart-e2guardian

- name: CONFIGURE | Web templates deployed
  ansible.builtin.template:
    src: opt/e2g/share/e2guardian/languages/ukenglish/{{ item }}.j2
    dest: "{{ e2g_install_dir }}/share/e2guardian/languages/ukenglish/{{ item }}"
    owner: root
    group: root
    mode: "0644"
    backup: true
  loop:
    - neterr_template.html
    - template.html
  notify: restart-e2guardian
