---

# Deploys E2Guardian's main filter lists.

- name: CONFIGURE | Configuration templates deployed
  ansible.builtin.template:
    src: opt/e2guardian/etc/e2guardian/{{ item }}.j2
    dest: "{{ (e2g_install_dir, 'etc', 'e2guardian', item) | path_join }}"
    owner: root
    group: root
    mode: "0640"
  loop:
    - e2guardian.conf
    - lists/authplugins/ipgroups
  tags: e2g_config_templates
  notify: restart-e2guardian

- name: CONFIGURE | Default list templates deployed
  ansible.builtin.template:
    src: opt/e2guardian/etc/e2guardian/lists/{{ item }}.j2
    dest: "{{ (e2g_install_dir, 'etc', 'e2guardian', 'lists', 'example.group', item) | path_join }}"
    owner: root
    group: root
    mode: "0640"
  loop:
    - addheaderregexplist
    - bannedextensionlist
    - bannedmimetypelist
    - bannedphraselist
    - bannedregexpheaderlist
    - bannedregexpurllist
    - bannedregexpuseragentlist
    - bannedsearchlist
    - bannedsiteiplist
    - bannedsitelist
    - bannedsslsiteiplist
    - bannedsslsitelist
    - bannedtimelist
    - bannedurllist
    - blankettimelist
    - contentregexplist
    - domainsnobypass
    - exceptionextensionlist
    - exceptionfilesiteiplist
    - exceptionfilesitelist
    - exceptionfileurllist
    - exceptionmimetypelist
    - exceptionphraselist
    - exceptionregexpheaderlist
    - exceptionregexpurllist
    - exceptionregexpuseragentlist
    - exceptionsiteiplist
    - exceptionsitelist
    - exceptionurllist
    - exceptionvirusextensionlist
    - exceptionvirussiteiplist
    - greysiteiplist
    - greysitelist
    - greysslsiteiplist
    - greysslsitelist
    - greyurllist
    - headerregexplist
    - ipnobypass
    - logregexpurllist
    - logsiteiplist
    - logsitelist
    - logurllist
    - nocheckcertsiteiplist
    - nocheckcertsitelist
    - refererexceptionsiteiplist
    - refererexceptionsitelist
    - refererexceptionurllist
    - responseheaderregexplist
    - sslsiteregexplist
    - urlnobypass
    - urlredirectregexplist
    - urlregexplist
    - weightedphraselist
  tags: e2g_config_templates
  notify: restart-e2guardian

- name: CONFIGURE | Web templates deployed
  ansible.builtin.template:
    src: opt/e2guardian/share/e2guardian/languages/ukenglish/{{ item }}.j2
    dest: "{{ (e2g_install_dir, 'share', 'e2guardian', 'languages', 'ukenglish', item) | path_join }}"
    owner: root
    group: root
    mode: "0640"
  loop:
    - neterr_template.html
    - template.html
  tags: e2g_config_templates
  notify: restart-e2guardian
