---

- name: FILTER_GROUPS | Filter group configuration file created
  ansible.builtin.template:
    src: opt/e2g/etc/e2guardian/e2guardianfn.conf.j2
    dest: "{{ e2g_install_dir }}/etc/e2guardian/e2guardianf{{ item_index + 1}}.conf"
  notify: restart-e2guardian

# ------------------------------------------------------------------------------

- name: FILTER_GROUPS | banned_sitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.banned_sitelist.path }}"
    content: "{{ item.lists.banned_sitelist.content | default('') }}"
  when:
    - item.lists.banned_sitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | banned_phraselist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.banned_phraselist.path }}"
    content: "{{ item.lists.banned_phraselist.content | default('') }}"
  when:
    - item.lists.banned_phraselist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | weighted_phraselist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.weighted_phraselist.path }}"
    content: "{{ item.lists.weighted_phraselist.content | default('') }}"
  when:
    - item.lists.weighted_phraselist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | exception_phraselist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.exception_phraselist.path }}"
    content: "{{ item.lists.exception_phraselist.content | default('') }}"
  when:
    - item.lists.exception_phraselist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | banned_sitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.banned_sitelist.path }}"
    content: "{{ item.lists.banned_sitelist.content | default('') }}"
  when:
    - item.lists.banned_sitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | banned_ipsitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.banned_ipsitelist.path }}"
    content: "{{ item.lists.banned_ipsitelist.content | default('') }}"
  when:
    - item.lists.banned_ipsitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | banned_urllist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.banned_urllist.path }}"
    content: "{{ item.lists.banned_urllist.content | default('') }}"
  when:
    - item.lists.banned_urllist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | banned_regexpboollist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.banned_regexpboollist.path }}"
    content: "{{ item.lists.banned_regexpboollist.content | default('') }}"
  when:
    - item.lists.banned_regexpboollist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | banned_useragent_regexpboollist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.banned_useragent_regexpboollist.path }}"
    content: "{{ item.lists.banned_useragent_regexpboollist.content | default('') }}"
  when:
    - item.lists.banned_useragent_regexpboollist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | banned_ssl_sitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.banned_ssl_sitelist.path }}"
    content: "{{ item.lists.banned_ssl_sitelist.content | default('') }}"
  when:
    - item.lists.banned_ssl_sitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | banned_ssl_ipsitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.banned_ssl_ipsitelist.path }}"
    content: "{{ item.lists.banned_ssl_ipsitelist.content | default('') }}"
  when:
    - item.lists.banned_ssl_ipsitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | grey_sitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.grey_sitelist.path }}"
    content: "{{ item.lists.grey_sitelist.content | default('') }}"
  when:
    - item.lists.grey_sitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | grey_ipsitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.grey_ipsitelist.path }}"
    content: "{{ item.lists.grey_ipsitelist.content | default('') }}"
  when:
    - item.lists.grey_ipsitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | grey_urllist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.grey_urllist.path }}"
    content: "{{ item.lists.grey_urllist.content | default('') }}"
  when:
    - item.lists.grey_urllist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | grey_ssl_sitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.grey_ssl_sitelist.path }}"
    content: "{{ item.lists.grey_ssl_sitelist.content | default('') }}"
  when:
    - item.lists.grey_ssl_sitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | grey_ssl_ipsitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.grey_ssl_ipsitelist.path }}"
    content: "{{ item.lists.grey_ssl_ipsitelist.content | default('') }}"
  when:
    - item.lists.grey_ssl_ipsitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | exception_sitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.exception_sitelist.path }}"
    content: "{{ item.lists.exception_sitelist.content | default('') }}"
  when:
    - item.lists.exception_sitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | exception_ipsitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.exception_ipsitelist.path }}"
    content: "{{ item.lists.exception_ipsitelist.content | default('') }}"
  when:
    - item.lists.exception_ipsitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | exception_urllist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.exception_urllist.path }}"
    content: "{{ item.lists.exception_urllist.content | default('') }}"
  when:
    - item.lists.exception_urllist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | exception_regexpboollist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.exception_regexpboollist.path }}"
    content: "{{ item.lists.exception_regexpboollist.content | default('') }}"
  when:
    - item.lists.exception_regexpboollist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | exception_useragent_regexpboollist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.exception_useragent_regexpboollist.path }}"
    content: "{{ item.lists.exception_useragent_regexpboollist.content | default('') }}"
  when:
    - item.lists.exception_useragent_regexpboollist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | reference_exception_sitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.reference_exception_sitelist.path }}"
    content: "{{ item.lists.reference_exception_sitelist.content | default('') }}"
  when:
    - item.lists.reference_exception_sitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | reference_exception_ipsitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.reference_exception_ipsitelist.path }}"
    content: "{{ item.lists.reference_exception_ipsitelist.content | default('') }}"
  when:
    - item.lists.reference_exception_ipsitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | reference_exception_urllist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.reference_exception_urllist.path }}"
    content: "{{ item.lists.reference_exception_urllist.content | default('') }}"
  when:
    - item.lists.reference_exception_urllist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | embeded_reference_exception_sitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.embeded_reference_exception_sitelist.path }}"
    content: "{{ item.lists.embeded_reference_exception_sitelist.content | default('') }}"
  when:
    - item.lists.embeded_reference_exception_sitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | embeded_reference_exception_ipsitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.embeded_reference_exception_ipsitelist.path }}"
    content: "{{ item.lists.embeded_reference_exception_ipsitelist.content | default('') }}"
  when:
    - item.lists.embeded_reference_exception_ipsitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | embeded_reference_exception_urllist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.embeded_reference_exception_urllist.path }}"
    content: "{{ item.lists.embeded_reference_exception_urllist.content | default('') }}"
  when:
    - item.lists.embeded_reference_exception_urllist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | modification_regexpreplacelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.modification_regexpreplacelist.path }}"
    content: "{{ item.lists.modification_regexpreplacelist.content | default('') }}"
  when:
    - item.lists.modification_regexpreplacelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | modification_ssl_regexpreplacelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.modification_ssl_regexpreplacelist.path }}"
    content: "{{ item.lists.modification_ssl_regexpreplacelist.content | default('') }}"
  when:
    - item.lists.modification_ssl_regexpreplacelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | redirect_regexpreplacelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.redirect_regexpreplacelist.path }}"
    content: "{{ item.lists.redirect_regexpreplacelist.content | default('') }}"
  when:
    - item.lists.redirect_regexpreplacelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | redirect_contentregexplist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.redirect_contentregexplist.path }}"
    content: "{{ item.lists.redirect_contentregexplist.content | default('') }}"
  when:
    - item.lists.redirect_contentregexplist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | local_sitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.local_sitelist.path }}"
    content: "{{ item.lists.local_sitelist.content | default('') }}"
  when:
    - item.lists.local_sitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | local_searchlist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.local_searchlist.path }}"
    content: "{{ item.lists.local_searchlist.content | default('') }}"
  when:
    - item.lists.local_searchlist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | local_grey_sitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.local_grey_sitelist.path }}"
    content: "{{ item.lists.local_grey_sitelist.content | default('') }}"
  when:
    - item.lists.local_grey_sitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | local_grey_sitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.local_grey_sitelist.path }}"
    content: "{{ item.lists.local_grey_sitelist.content | default('') }}"
  when:
    - item.lists.local_grey_sitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | local_exception_sitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.local_exception_sitelist.path }}"
    content: "{{ item.lists.local_exception_sitelist.content | default('') }}"
  when:
    - item.lists.local_exception_sitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | fileextlist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.fileextlist.path }}"
    content: "{{ item.lists.fileextlist.content | default('') }}"
  when:
    - item.lists.fileextlist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | mimelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.mimelist.path }}"
    content: "{{ item.lists.mimelist.content | default('') }}"
  when:
    - item.lists.mimelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | exception_file_sitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.exception_file_sitelist.path }}"
    content: "{{ item.lists.exception_file_sitelist.content | default('') }}"
  when:
    - item.lists.exception_file_sitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | exception_file_ipsitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.exception_file_ipsitelist.path }}"
    content: "{{ item.lists.exception_file_ipsitelist.content | default('') }}"
  when:
    - item.lists.exception_file_ipsitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | exception_file_urllist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.exception_file_urllist.path }}"
    content: "{{ item.lists.exception_file_urllist.content | default('') }}"
  when:
    - item.lists.exception_file_urllist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | header_regexpreplacelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.header_regexpreplacelist.path }}"
    content: "{{ item.lists.header_regexpreplacelist.content | default('') }}"
  when:
    - item.lists.header_regexpreplacelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | banned_header_regexpboollist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.banned_header_regexpboollist.path }}"
    content: "{{ item.lists.banned_header_regexpboollist.content | default('') }}"
  when:
    - item.lists.banned_header_regexpboollist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | exception_header_regexpboollist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.exception_header_regexpboollist.path }}"
    content: "{{ item.lists.exception_header_regexpboollist.content | default('') }}"
  when:
    - item.lists.exception_header_regexpboollist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | add_header_regexpreplacelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.add_header_regexpreplacelist.path }}"
    content: "{{ item.lists.add_header_regexpreplacelist.content | default('') }}"
  when:
    - item.lists.add_header_regexpreplacelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | search_regexpreplacelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.search_regexpreplacelist.path }}"
    content: "{{ item.lists.search_regexpreplacelist.content | default('') }}"
  when:
    - item.lists.search_regexpreplacelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | banned_searchlist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.banned_searchlist.path }}"
    content: "{{ item.lists.banned_searchlist.content | default('') }}"
  when:
    - item.lists.banned_searchlist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | override_searchlist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.override_searchlist.path }}"
    content: "{{ item.lists.override_searchlist.content | default('') }}"
  when:
    - item.lists.override_searchlist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | banned_bypass_sitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.banned_bypass_sitelist.path }}"
    content: "{{ item.lists.banned_bypass_sitelist.content | default('') }}"
  when:
    - item.lists.banned_bypass_sitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | nocheckcert_sitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.nocheckcert_sitelist.path }}"
    content: "{{ item.lists.nocheckcert_sitelist.content | default('') }}"
  when:
    - item.lists.nocheckcert_sitelist.path is defined
  notify: restart-e2guardian

- name: FILTER_GROUPS | nocheckcert_ipsitelist filter group file created
  ansible.builtin.copy:
    dest: "{{ item.lists.nocheckcert_ipsitelist.path }}"
    content: "{{ item.lists.nocheckcert_ipsitelist.content | default('') }}"
  when:
    - item.lists.nocheckcert_ipsitelist.path is defined
  notify: restart-e2guardian
