---

# Clone, build, and install E2Guardian.

- name: INSTALL | Necessary packages present
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - "{{ e2g_build_dependencies }}"
    - "{{ e2g_runtime_dependencies }}"
    # Libpcre must be installed after everything else on Ubuntu.
    - "{{ e2g_additional_dependencies }}"
  when: build_e2g

- name: INSTALL | Group present
  ansible.builtin.group:
    name: "{{ e2g_conf_daemongroup }}"

- name: INSTALL | User present
  ansible.builtin.user:
    name: "{{ e2g_conf_daemonuser }}"
    shell: /usr/sbin/nologin
    create_home: false
    group: "{{ e2g_conf_daemongroup }}"

- name: INSTALL | Paths configured
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "0750"
  loop:
    - path: "{{ e2g_install_dir }}"
      owner: root

    - path: "{{ e2g_conf_loglocation | dirname }}"
      owner: "{{ e2g_conf_daemonuser }}"

    - path: /var/log/e2guardian
      owner: "{{ e2g_conf_daemonuser }}"
  when: item.path is defined

- name: INSTALL | E2Guardian built
  block:
    - name: INSTALL | BUILD | E2Guardian Repo cloned
      ansible.builtin.git:
        repo: "{{ e2g_repo_url }}"
        dest: "{{ e2g_repo_dir }}"
        accept_hostkey: true
        version: "{{ e2g_repo_branch }}"
        depth: 1
        force: true

    - name: INSTALL | BUILD | Build options configured
      shell:
        cmd: "{{ item }}"
        chdir: "{{ e2g_repo_dir }}"
      loop:
        - ./autogen.sh
        - ./configure {{ build_options }}

    - name: INSTALL | BUILD | E2Guardian built
      community.general.make:
        chdir: "{{ e2g_repo_dir }}"
        jobs: "{{ ansible_processor_vcpus | int + 1 }}"

    - name: INSTALL | BUILD | E2Guardian installed
      shell:
        cmd: make install
        chdir: "{{ e2g_repo_dir }}"
      notify: restart-e2guardian
  when: build_e2g

- name: INSTALL | Unit file deployed
  ansible.builtin.copy:
    src: "{{ (e2g_repo_dir, 'data', 'scripts', 'e2guardian.service') | path_join }}"
    dest: /etc/systemd/system/e2guardian.service
    remote_src: true
    owner: root
    group: root
    mode: "0640"
  notify: restart-e2guardian

- name: INSTALL | Unit file override path exists.
  ansible.builtin.file:
    path: /etc/systemd/system/e2guardian.service.d
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: INSTALL | Unit file override deployed.
  ansible.builtin.template:
    src: etc/systemd/system/e2guardian.service.d/override.conf.j2
    dest: /etc/systemd/system/e2guardian.service.d/override.conf
    owner: root
    group: root
    mode: "0640"
  notify: restart-e2guardian

- name: INSTALL | Build dependencies removed
  ansible.builtin.apt:
    name: "{{ e2g_build_dependencies }}"
    state: absent
    autoremove: true
    purge: true
  when: remove_build_dependencies

- name: INSTALL | Helper script deployed
  ansible.builtin.copy:
    src: edit-e2g-lists.sh
    dest: /edit-e2g-lists.sh
    owner: root
    group: root
    mode: "0755"

- name: INSTALL | {{ e2g_install_dir }} to added to $PATH
  ansible.builtin.template:
    src: etc/profile.d/e2g-path.sh.j2
    dest: /etc/profile.d/e2g-path.sh
    owner: root
    group: root
    mode: "0644"

- name: INSTALL | E2Guardian allowed in ufw
  community.general.ufw:
    rule: allow
    proto: tcp
    to_port: "{{ item }}"
  loop: "{{ e2g_conf_filterports }}"
