---

- name: MAIN | Set facts
  block:
    - name: MAIN | Set FreeBSD facts
      set_fact:
        root_group: wheel  # FreeBSD hosts don't have a root group.
        profiled_path: /usr/local/etc/profile.d
      when: ansible_system == "FreeBSD"

    - name: MAIN | Set Linux facts
      set_fact:
        root_group: root
        profiled_path: /etc/profile.d
      when: ansible_system == "Linux"

- name: MAIN | Import install.yml
  import_tasks: install.yml
  when: e2g_include_install_tasks

- name: MAIN | Import configure.yml
  import_tasks: configure.yml
  when: e2g_include_configure_tasks

- name: MAIN | Import filter_groups.yml
  include_tasks: filter_groups.yml
  loop: "{{ e2g_filter_groups }}"
  loop_control:
    index_var: item_index
  when: e2g_include_filter_groups_tasks

- name: MAIN | Import webserver.yml
  import_tasks: webserver.yml
  when: e2g_include_webserver_tasks

- name: MAIN | E2Guardian service enabled and running
  service:
    name: e2guardian
    enabled: true
    state: started
