---

- name: MAIN | Import install.yml
  import_tasks: install.yml
  when: e2g_include_install_tasks

- name: MAIN | Import configure.yml
  import_tasks: configure.yml
  when: e2g_include_configure_tasks

- name: MAIN | Import filter_groups.yml
  include_tasks: filter_groups.yml
  loop: "{{ e2g_filter_groups }}"
  loop_control:
    index_var: item_index
  when: e2g_include_filter_groups_tasks

- name: MAIN | Import webserver.yml
  import_tasks: webserver.yml
  when:
    - e2g_include_webserver_tasks
    - e2g_conf_enablessl is defined
    - e2g_conf_enablessl

- name: MAIN | Import certs.yml
  import_tasks: certs.yml
  when:
    - e2g_include_certs_tasks
    - e2g_conf_enablessl is defined
    - e2g_conf_enablessl

- name: MAIN | E2Guardian service enabled and running
  ansible.builtin.systemd:
    name: e2guardian
    enabled: true
    state: started
    daemon_reload: true
    masked: false
