---

- name: MAIN | Import install.yml
  import_tasks: install.yml
  tags: install

- name: MAIN | Import configure.yml
  import_tasks: configure.yml
  tags: configure

- name: MAIN | Import filter_groups.yml
  include_tasks: filter_groups.yml
  loop: "{{ e2g_filter_groups }}"
  loop_control:
    index_var: item_index
  tags: filter

- name: MAIN | Import webserver.yml
  import_tasks: webserver.yml
  tags: webserver
  when:
    - e2g_conf_enablessl is defined
    - e2g_conf_enablessl

- name: MAIN | Import certs.yml
  import_tasks: certs.yml
  tags: certs
  when:
    - e2g_conf_enablessl is defined
    - e2g_conf_enablessl

- name: MAIN | E2Guardian service enabled and running
  ansible.builtin.systemd:
    name: e2guardian
    enabled: true
    state: started
    daemon_reload: true
    masked: false
  tags: services

- name: MAIN | Import uninstall.yml
  import_tasks: uninstall.yml
  when: uninstall_e2g
  tags: never
