---

# Example dictionary:
# e2g_misc_files:
#   - name: bannedregexpurllist_include_01
#     groupname: eris_group
#     content:
#       - "#time: 15 00 23 59 0123456"
#       - youtube\.com
#       - youtu\.be
#   - filename: bannedregexpurllist_include_02
#     groupname: eris_group
#     content:
#       - "#time: 00 00 11 00 0123456"
#       - youtube\.com
#       - youtu\.be

- name: MISC_FILES | Misc files created for filter groups
  ansible.builtin.copy:
    dest: "{{ (e2g_list_dir_root, (item.groupname + '.group'), item.name) | path_join }}"
    content: |
      {%- for line in item.content %}
      {{ line }}
      {% endfor -%}
    mode: "0640"
  when:
    - item.name is defined
    - item.name != ""
    - e2g_misc_files is defined
    - e2g_misc_files != ""
  loop_control:
    label: "{{ item.groupname }} --> {{ item.name }}"
  loop: "{{ e2g_misc_files }}"
  notify: restart-e2guardian
