---

# Uninstall E2Guardian.

- name: UNINSTALL | Service stopped
  ansible.builtin.systemd:
    name: e2guardian
    enabled: false
    state: stopped
    daemon_reload: true
    masked: false
  ignore_errors: true  # Task will fail if service already doesn't exist.

- name: UNINSTALL | Package absent
  ansible.builtin.apt:
    name: e2guardian
    state: absent
    autoremove: true

- name: UNINSTALL | E2Guardian user absent
  ansible.builtin.user:
    name: "{{ e2g_conf_daemonuser }}"
    state: absent

- name: UNINSTALL | E2Guardian group absent
  ansible.builtin.group:
    name: "{{ e2g_conf_daemongroup }}"
    state: absent

- name: UNINSTALL | Paths removed
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ e2g_install_dir }}"
    - /etc/nginx/sites-available/e2guardian
    - /etc/nginx/sites-enabled/e2guardian
    - /etc/profile.d/e2g-path.sh
    - /etc/systemd/system/e2guardian.service
    - /etc/systemd/system/e2guardian.service.d
    - /var/log/e2guardian
    - /var/www/e2guardian

- name: UNINSTALL | E2Guardian UFW rules removed
  community.general.ufw:
    rule: allow
    proto: tcp
    to_port: "{{ item }}"
    delete: true
  when: ufw_check.rc == 0
  loop: "{{ e2g_conf_filterports }}"

- name: UNINSTALL | Webserver ufw rules removed
  community.general.ufw:
    rule: allow
    proto: tcp
    to_port: 80
    delete: true
  when: ufw_check.rc == 0
