---

# Installs and configures Nginx for serving E2Guardian's public certificate.
#
# This is only useful if E2Guardian's SSL man-in-the-middle feature is being
#   used.

  ansible.builtin.package:
- name: WEBSERVER | Nginx package present
    name: nginx
  notify: restart-webserver

- name: WEBSERVER | Nginx site configured
  ansible.builtin.file:
    path: /var/www/e2guardian
    state: directory
    owner: www-data
    group: www-data
    mode: "0750"
  notify: restart-webserver

- name: WEBSERVER | Nginx template deployed
  ansible.builtin.template:
    src: etc/nginx/sites-available/e2guardian.j2
    dest: /etc/nginx/sites-available/e2guardian
    owner: root
    group: root
    mode: "0640"
  notify: restart-webserver

- name: WEBSERVER | Nginx default site disabled
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart-webserver

- name: WEBSERVER | Nginx E2Guardian site enabled
  ansible.builtin.file:
    src: /etc/nginx/sites-available/e2guardian
    dest: /etc/nginx/sites-enabled/e2guardian
    state: link
  notify: restart-webserver

- name: WEBSERVER | Nginx allowed through UFW
  community.general.ufw:
    rule: allow
    proto: tcp
    to_port: 80
  when: ufw_check.rc == 0
