---

# Static Nginx webserver for serving E2Guardian's public certificate.
# Only useful if SSL man-in-the-middle is used.

- name: WEBSERVER | Nginx package installed
  ansible.builtin.package:
    name: nginx
  notify: restart-webserver

- name: WEBSERVER | Nginx site configured
  ansible.builtin.file:
    path: /var/www/e2guardian
    state: directory
    owner: www-data
    group: www-data
    mode: "0750"
  notify: restart-webserver

- name: WEBSERVER | Nginx template deployed
  ansible.builtin.template:
    src: etc/nginx/sites-available/e2guardian.j2
    dest: /etc/nginx/sites-available/e2guardian
    owner: root
    group: root
    mode: "0640"
  notify: restart-webserver

- name: WEBSERVER | Nginx default site disabled
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart-webserver

- name: WEBSERVER | Nginx E2Guardian site enabled
  ansible.builtin.file:
    src: /etc/nginx/sites-available/e2guardian
    dest: /etc/nginx/sites-enabled/e2guardian
    state: link
  notify: restart-webserver

- name: WEBSERVER | Nginx allowed in ufw
  community.general.ufw:
    rule: allow
    proto: tcp
    to_port: 80
