---

# Static webserver for serving E2Guardian's public certificate.

- name: WEBSERVER | Nginx package installed
  ansible.builtin.package:
    name: nginx
  notify: restart-webserver

- name: WEBSERVER | Nginx paths configured
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "0755"
  loop:
    - path: /var/www/e2guardian
      owner: www-data
  notify: restart-webserver

- name: WEBSERVER | Nginx templates deployed
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /{{ item }}
    owner: root
    group: root
    mode: "0644"
  loop:
    - etc/nginx/nginx.conf
  notify: restart-webserver
