---

- name: Converge
  hosts: all
  become: true
  vars:
    e2g_build_package: true
  tasks:
    - name: Include e2guardian
      ansible.builtin.include_role:
        name: ansible-role-e2guardian
