---

- name: HANDLERS | E2Guardian stopped
  ansible.builtin.shell:
    cmd: /usr/bin/e2guardian -c {{ (e2g_install_dir, "etc", "e2guardian", "e2guardian.conf") | path_join }} -q
  listen: restart-e2guardian

- name: HANDLERS | E2Guardian started
  ansible.builtin.systemd:
    name: e2guardian
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
  listen: restart-e2guardian

- name: HANDLERS | Webserver restarted
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
  listen: restart-webserver

- name: HANDLERS | Systemd-journald restarted
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
  listen: restart-journald
