---

- name: HANDLERS | E2Guardian restarted
  block:
    - name: HANDLERS | E2Guardian stopped
      ansible.builtin.shell:
        cmd: /usr/bin/e2guardian -c {{ (e2g_install_dir, "etc", "e2guardian", "e2guardian.conf") | path_join }} -q
      listen: restart-e2guardian

    - name: HANDLERS | E2Guardian PID absent
      ansible.builtin.file:
        path: "{{ (e2g_install_dir, 'var', 'run', 'e2guardian.pid') | path_join }}"
        state: absent
      listen: restart-e2guardian

    - name: HANDLERS | E2Guardian started
      ansible.builtin.systemd:
        name: e2guardian
        state: restarted
        enabled: true
        masked: false
        daemon_reload: true
      listen: restart-e2guardian

    - name: HANDLERS | E2Guardian accepting connections
      ansible.builtin.wait_for:
        host: "{{ e2g_conf_filterip[0] | default('0.0.0.0') }}"
        port: "{{ e2g_conf_filterports[0] | default('8080') | int }}"
        connect_timeout: 3
        timeout: 30
      listen: restart-e2guardian

- name: HANDLERS | Webserver restarted
  block:
    - name: HANDLERS | Webserver service restarted
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: true
        masked: false
        daemon_reload: true
      listen: restart-webserver

    - name: HANDLERS | Webserver accepting connections
      ansible.builtin.uri:
        url: http://localhost:80
        status_code: 200
      register: result
      until: result.status == 200
      retries: 10
      delay: 3
      listen: restart-webserver

- name: HANDLERS | Systemd-journald restarted
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
  listen: restart-journald
