---

- name: Converge
  hosts: all
  become: true
  become_method: su
  gather_facts: true
  tasks:
    - name: Include e2guardian
      ansible.builtin.include_role:
        name: ansible-role-e2guardian
