---

- name: Verify
  hosts: all
  become: true
  become_method: su
  gather_facts: true
  tasks:

    - name: MOLECULE | VERIFY | Test webserver
      ansible.builtin.shell: >
        curl
        -L
        --silent
        --insecure
        http://localhost/cert.pem |
        grep -A 10 "CERTIFICATE"
      changed_when: false
      environment:
        HTTP_PROXY: http://localhost:8080
        HTTPS_PROXY: http://localhost:8080

    - name: MOLECULE | VERIFY | Test allowed page
      ansible.builtin.shell: >
        curl
        -L
        --silent
        --insecure
        https://duckduckgo.com |
        grep -q "DuckDuckGo"
      changed_when: false
      environment:
        HTTP_PROXY: http://localhost:8080
        HTTPS_PROXY: http://localhost:8080

    - name: MOLECULE | VERIFY | Confirm allowed page in log
      ansible.builtin.shell: >
        journalctl -u e2guardian --no-pager | grep "duckduckgo" | grep "TRUSTED"
      changed_when: false

    - name: MOLECULE | VERIFY | Test blocked page
      ansible.builtin.shell: >
        curl
        -L
        --silent
        --insecure
        https://google.com |
        grep -q "Blocked site"
      changed_when: false
      environment:
        HTTP_PROXY: http://localhost:8080
        HTTPS_PROXY: http://localhost:8080

    - name: MOLECULE | VERIFY | Confirm blocked page in log
      ansible.builtin.shell: >
        journalctl -u e2guardian --no-pager | grep "google" | grep "DENIED"
      changed_when: false
