---

on:
  push:
    paths-ignore:
      - '**.gitignore'
      - '**.md'
      - '**.rst'
      - LICENSE

jobs:
  ansible_lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            tasks
            handlers
            defaults
          args: ""

  molecule:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}

      - name: Run molecule
        uses: MonolithProjects/action-molecule@v1.4.4
        # with:
          # molecule_command: converge
